### PR TITLE
Reset query by clicking logo

### PR DESCRIPTION
**Pull request by dan-nyanko**
Adds a feature to reset the filter when clicking the logo

### CODE REVIEW

**Comment by dan-nyanko** [comment]
https://www.pivotaltracker.com/story/show/123081451

**Comment by dan-nyanko** [comment]
https://www.pivotaltracker.com/story/show/118648433

**Comment by Broham** [comment]
@dan-nyanko looks like this branch has some conflicts after the last two merges.  If you can get them resolved I will merge.  Thanks

**Comment by dan-nyanko** [comment]
@Broham bump

**Pull request merged**
