### PR TITLE
New sidebar package

### PR DESCRIPTION
**Pull request by jgoley**
This PR refactors the sidebars in flirt. I created a package that basically just sets up the framework (styles, base-template, etc) for sidebars then another app-specific package that adds the content and changes colors.

Now the state of sidebars is controlled by a few lines of coffeescript and CSS. In the future we could probably rework the `eha:sidebar` package to be even more modular.

I made some updates to the grits-net-meteor repo to accomodate these changes which may affect SPA and/or BIRT.

Also...I went ahead and moved the mode toggle buttons to the sidebar. We can change this if this is deemed unacceptable.

### CODE REVIEW

**Comment by nathanathan** [comment]
It looks like the grits-net-meteor package manifest needs to be updated to remove the old sidebar package. I'm getting this error:

```
   While selecting package versions:
   error: unknown package: grits:flirt-sidebar
   Required by: grits:grits-net-meteor 0.0.1
```

**Comment by nathanathan** [comment]
I removed the package and I'm seeing a couple other issues. There are multiple title images and font color on the unselected toggle button is too close to the background color to be easily distinguishable. I like the new toggle buttons.

**Comment by jgoley** [comment]
@nathanathan Those styling errors were occurring because the `grits-net-meteor` package was not aligned with the master branch of the `grits-net-meteor` repo. I've updated the the `grits-net-meteor` package with the repo (using this branch: https://github.com/ecohealthalliance/grits-net-meteor/pull/172 — which simply removes the flirt-sidebar package from the example app as you mentioned).
All seems well now.

**Comment by nathanathan** [comment]
:+1:

**Pull request merged**
