### PR TITLE
Add airport property search tokens

### PR DESCRIPTION
**Pull request by nathanathan**
Related story: https://www.pivotaltracker.com/story/show/138515131

### CODE REVIEW

**Comment by Broham** [comment]
Is the confirmation box intended to be included in production or was this for testing?  If we want it in production, would it make sense to have @jgoley style this to make it a little prettier?

**Comment by jgoley** [comment]
We should replace it with a modal. I can take care of that if we want to keep the user choice.

**Comment by Broham** [comment]
@jgoley why don't you go ahead and implement that - I'm pretty sure Nathan wants it in production

**Comment by jgoley** [comment]
I've noticed the user has to enter the entire territory name before it appears in the results. Maybe we should change up the result hierarchy to show these results first?

**Comment by Broham** [comment]
Looks good - thanks @jgoley!  @nathanathan - do we want to implement partial matches on regions?  So if you type `Cali` then `California` would come up?

**Pull request merged**
